config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  resources :quizzes
  resources :prompts
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  post "quizzes/:id/check_answer", to: "quizzes#check_answer", as: "check_answer"
  get "quizzes/:id/reset_quiz_questions", to: "quizzes#reset_quiz_questions", as: "reset_quiz_questions"
  get "quizzes/:id/activate", to: "quizzes#activate", as: "activate_quiz"
  get "quizzes/:id/add_questions", to: "quizzes#add_questions", as: "add_questions_quiz"
  get "quizzes/:id/subscribe", to: "quizzes#subscribe", as: "subscribe"
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: %i[ show edit update destroy check_answer reset_quiz_questions activate add_questions subscribe]
  before_action :set_prompts, only: %i[show check_answer reset_quiz_questions]
  before_action :set_score, only: %i[show check_answer reset_quiz_questions]
  before_action :authenticate_user!, only: %i[create edit update new subscribe]

  # GET /quizzes or /quizzes.json
  def index
    @quizzes = Quiz.all

    # instead, show the specific quizzes that are available to a user
    if current_user.present?
      # @owned_quizzes = Quiz.where(user: current_user).last(10)
      @subscribed_quizzes = Quiz.joins(:quizzes_users).where(quizzes_users: {user_id: current_user.id})
    end

    # Next up, make a way to subscribe to a quiz
  end

  # GET /quizzes/1 or /quizzes/1.json
  def show
    

  end

  #make a my_quizzes action, which shows the created quizzes

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes or /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to add_questions_quiz_path(@quiz), notice: "Quiz was successfully created." }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  def check_answer

    @prompt = @prompts.first
    @score = session['current_score']
    # debugger
    if @prompt.check_answer(params[:prompt][:answer_attempt])
      @score += 1
    end

    @prompts = @prompts.drop(1)
    session['prompt_ids'] = @prompts.map{|prompt| prompt.id}
  
    session['current_score'] = @score
    respond_to do |format|
      format.html { redirect_to quiz_url(@quiz)}
    end
  end

  # PATCH/PUT /quizzes/1 or /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to quiz_url(@quiz), notice: "Quiz was successfully updated." }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1 or /quizzes/1.json
  def destroy
    @quiz.destroy

    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: "Quiz was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def reset_quiz_questions
    session['prompt_ids'] = nil
    reset_score
    @prompts = Prompt.last(2)
   
    respond_to do |format|
      format.html { redirect_to quiz_url(@quiz), notice: "Quiz questions were successfully reset." }
    end
  end

  def activate
    @quiz.activate
  end

  def deactivate
    @quiz.deactivate
  end

  def add_questions
    @prompt = Prompt.new
    @prompts = @quiz.prompts.order(create_at: :desc)
    
  end

  def subscribe
    # set the user
    @current_user = current_user
    # Create a new QuizzesUser and set the user and quiz
    quizzes_user = QuizzesUsers.new(quiz: @quiz, user: @current_user)
    if quizzes_user.save!
      # render success
      # or is there a way to do this with json, so that we only get the green checkmark
      respond_to do |format|
        format.html { redirect_to quizzes_url, notice: "Subscribed successfully!" }
      end

    else
      # render same page with an error message
      format.html { render :new, status: :unprocessable_entity }

    end
  end

  def unsubscribe
    #set quiz somehow
    @user.unsubscribe(quiz)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    def set_prompts
      if session['prompt_ids'].present? && session['prompt_ids'].count > 0
        @prompts = Prompt.find(session['prompt_ids'])
      elsif session['prompt_ids']&.empty?
        @prompts = []
      else
        @prompts = @prompts ||= @quiz.prompts
      end
    end

    def set_score
      @score = session['current_score'] || 0
    end

    # Only allow a list of trusted parameters through.
    def quiz_params
      params.require(:quiz).permit(:name)
    end

    def reset_score
      session['current_score'] = 0
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_completed.html.erb
<div>
  You've completed all the questions.
  Your Score: <b><%= @score %></b> points
  <br>
  <%= link_to "Reset Quiz Questions", reset_quiz_questions_path(@quiz) %>

</div>

app/views/quizzes/_form.html.erb
<%= form_with(model: quiz) do |form| %>
  <% if quiz.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
        <% quiz.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/quizzes/_no_questions.html.erb
<div>
 <p> This quiz doesn't have any questions yet. </p>
 
  <%= link_to "Add questions", add_questions_quiz_path(@quiz) %>
  <br>
  <button><%= link_to "See All Quizzes", quizzes_path %></button>
</div>

app/views/quizzes/_question_partial.html.erb
  <div>
    <%= @prompts.first.question %>
  </div>

  <%= form_with(model: Prompt, url: check_answer_path ) do |form| %>
    <%= form.label :answer_attempt %>
    <%= form.text_field :answer_attempt %>

    <div>
      <%= form.submit "Guess" %>
    </div>
  <% end %>

app/views/quizzes/_quiz.html.erb
<div id="<%= dom_id quiz %>">
  <p>
    <strong>Name:</strong>
    <%= quiz.name %>
  </p>

</div>

app/views/quizzes/add_questions.html.erb
<%= turbo_stream_from :prompts %>

<p style="color: green"><%= notice %></p>
<b><%= @quiz.name %></b>
<br>
There are currently <b><%= @quiz.prompts.count %></b> questions in this quiz
<br>

<%= turbo_frame_tag :prompt_count do %>
    <%= @quiz.prompts.count %>
<% end %>

<p><%= link_to "Take this quiz", quiz_path(@quiz) %></p>
<br>

<%= turbo_frame_tag :prompt_form do %>
    <%= render "prompts/form", prompt: @prompt %>
<% end %>

<% if @quiz.prompts.count > 0 %>
    <b>Current Questions for this quiz</b>
    <%= turbo_frame_tag :prompts do %>
        <%= render @prompts %>
    <% end %>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Editing quiz</h1>

<%= render "form", quiz: @quiz %>

<br>

<div>
  <%= link_to "Show this quiz", @quiz %> |
  <%= link_to "Back to quizzes", quizzes_path %>
</div>

app/views/quizzes/index.html.erb
<p style="color: green"><%= notice %></p>

<% if @owned_quizzes.present? %>
  <h1>Quizzes you've made</h1>
  <div id="quizzes">
    <% @owned_quizzes.each do |quiz| %>
    
      <p>
        <%= link_to "#{quiz.name}", quiz %>
      </p>
    <% end %>
  </div>
<% end %>

<% if @subscribed_quizzes.present? %>
  <h1>Quizzes you've subscribed to</h1>

  <div id="quizzes">
    <% @subscribed_quizzes.each do |quiz| %>
    
      <p>
        <%= link_to "#{quiz.name}", quiz %>
      </p>
    <% end %>
  </div>
<% end %>
<h1>All Quizzes</h1>

<div id="quizzes">
  <% @quizzes.each do |quiz| %>
   
    <p>
      <%= link_to "#{quiz.name}", quiz %> 
      <% unless current_user && quiz.subscribed?%>
        <%= link_to "Subscribe", subscribe_path(quiz) %>
      <% end %>
    </p>
  <% end %>
</div>

<%= link_to "Create new Quiz", new_quiz_path %>

app/views/quizzes/new.html.erb
<h1>Create a new quiz</h1>

<%= render "form", quiz: @quiz %>

<br>

<div>
  <%= link_to "Back to quizzes", quizzes_path %>
</div>

app/views/quizzes/show.html.erb
<p style="color: green"><%= notice %></p>

<% if @prompts.count > 0 %>
  <%= render "question_partial" %>
<% elsif @quiz.prompts.count == 0 %>
  <%= render "no_questions" %>
<% else %>
  <%= render "completed" %>
<% end %>