config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  resources :quizzes
  resources :prompts
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  post "quizzes/:id/check_answer", to: "quizzes#check_answer", as: "check_answer"
  get "quizzes/:id/reset_quiz_questions", to: "quizzes#reset_quiz_questions", as: "reset_quiz_questions"
  get "quizzes/:id/activate", to: "quizzes#activate", as: "activate_quiz"
  get "quizzes/:id/add_questions", to: "quizzes#add_questions", as: "add_questions_quiz"
  get "quizzes/:id/subscribe", to: "quizzes#subscribe", as: "subscribe"
end

app/models/prompt.rb
class Prompt < ApplicationRecord
    validates_presence_of :question
    belongs_to :quiz

    after_create_commit { broadcast_prepend_to :prompts }

    def check_answer(answer_attempt)
      
        if self.answer.downcase == answer_attempt.downcase
            return true 
        else
            return false
        end
        
    end

    # add an alternative answer? Where two things could be accepted

    def check_for_alternative_answers
        self.answer.downcase == answer_attempt.downcase || self.answer.alternatives.contains?(answer_attempt)

        # add alternatives as an attribute. Make it an array of all possible alternatives?
        # Then add a way to have the array be updated. The question there is how to remove from the array when it is in the middle
    end

    # Now we need to connect quizzes and prompts with a join model
    # These go in alphabetical order
    # So it would be PromptQuiz as the join model name

    # We can also connect with users as QuizzesUsers

    # add it with
    # create_join_table :quizzes, :users

    #But then how to make it so that users subscribe to a quiz? And quizzes have subscribers?
    #generate a join model and a table? Or just one and the other comes with it?

    # Tried rails g migration CreateJoinTableQuizzesUsers quizzes users

    # and made:

    #class CreateJoinTableQuizzesUsers < ActiveRecord::Migration[7.0]
#   def change
#     create_join_table :quizzes, :users do |t|
#       # t.index [:quiz_id, :user_id]
#       # t.index [:user_id, :quiz_id]
#     end
#   end
# end

# but that is not quite what I need. I think I should add a model here too

# rails g model QuizzesUsers quizzes users

# the rails guide seems to be pointing me towards a has_and_belongs_to_many association

# this article seems to make has_many_through make more sense:
# https://stackoverflow.com/questions/35305439/create-join-table-using-migrations-or-models

#things I want to be able to do:
# show me all the quizzes a user made
# show me all the users that have take a quiz
# everytime a user takes a quiz, record it as a session. (Sessions can be incomplete)
# a quiz can have many subscribers
# a quiz can have many prompts
# change prompts to questions? but it is not just a question, but also an answer.

# I'm leaning toward a join model, since that will allow me to add methods if I ever need to. Next step
# is to create that join model and the table to go with it
end

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
  before_action :set_prompt, only: %i[ show edit update destroy ]

  # GET /prompts or /prompts.json
  def index
    @prompts = Prompt.all.order(create_at: :desc)
    @prompt = Prompt.new
  end

  # GET /prompts/1 or /prompts/1.json
  def show
    @prompt = Prompt.find(params[:id])
  end

  # GET /prompts/new
  def new
    @prompt = Prompt.new
  end

  # GET /prompts/1/edit
  def edit
    @prompt = Prompt.find(params[:id])
  end

  # POST /prompts or /prompts.json
  def create
    @prompt = Prompt.new(prompt_params)

    respond_to do |format|
      if @prompt.save
        format.html { redirect_to add_questions_quiz_path(@prompt.quiz), notice: "Question added successfully!" }
        format.json { render :show, status: :created, location: @prompt }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@prompt, partial: "prompts/form", locals: {prompt: @prompt}) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prompt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prompts/1 or /prompts/1.json
  def update
    respond_to do |format|
      if @prompt.update(prompt_params)
        format.html { redirect_to prompt_url(@prompt), notice: "Prompt was successfully updated." }
        format.json { render :show, status: :ok, location: @prompt }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prompt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prompts/1 or /prompts/1.json
  def destroy
    @prompt.destroy

    respond_to do |format|
      format.html { redirect_to prompts_url, notice: "Prompt was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prompt
      @prompt = Prompt.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prompt_params
      params.fetch(:prompt, {}).permit(:question, :answer, :quiz_id)
    end
end

app/helpers/prompts_helper.rb
module PromptsHelper
end

app/views/prompts/_form.html.erb
<%= form_with(model: prompt) do |form| %>
  <% if prompt.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(prompt.errors.count, "error") %> prohibited this prompt from being saved:</h2>

      <ul>
        <% prompt.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :prompt, style: "display: block" %>
    <%= form.text_area :question %>
  </div>

  <div>
    <%= form.label :answer, style: "display: block" %>
    <%= form.text_area :answer %>
  </div>



  <% if @quiz.present? %>
    <div>
      <%= form.label :quiz, style: "display: block" %>
      <%= form.number_field :quiz_id, :value => @quiz.id %>
    </div>
  <% else %>
    <div>
      <%= form.label :quiz, style: "display: block" %>
      <%= form.number_field :quiz_id, :value => Quiz.first.id %>
    </div>
  <% end %>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/prompts/_prompt.html.erb
<div style="background: lightgrey; width: 300px; padding: 10px;">
    Question: <%= prompt.question %>
    <br>
    Answer: <%= prompt.answer %>
    <br>
    Quiz id:<%= prompt.quiz_id %>
    <%= link_to :edit, edit_prompt_path(prompt) %>
</div>

app/views/prompts/edit.html.erb
<h1>Editing prompt</h1>

<%= render "form", prompt: @prompt %>

<br>

<div>
  <%= link_to "Show this prompt", @prompt %> |
  <%= link_to "Back to prompts", prompts_path %>
</div>

app/views/prompts/index.html.erb
<%= turbo_stream_from :prompts %>

<%= turbo_frame_tag :prompt_form do %>
  <%= render "prompts/form", prompt: @prompt %> 
<% end %>

<b>All Prompts</b>
<%= turbo_frame_tag :prompts do %>
    <%= render @prompts %>
<% end %>

app/views/prompts/new.html.erb
<h1>New prompt</h1>

<%= render "form", prompt: @prompt %>

<br>

<div>
  <%= link_to "Back to prompts", prompts_path %>
</div>

app/views/prompts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @prompt %>

<div>
  <%= link_to "Edit this prompt", edit_prompt_path(@prompt) %> |
  <%= link_to "Back to prompts", prompts_path %>

  <%= button_to "Destroy this prompt", @prompt, method: :delete %>
</div>